<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    public function run(): void
    {
        $currencies = [
            [
                'name' => 'USDT (TRC20)',
                'symbol' => 'USDT',
                'image' => '/uploads/coins/4ebb621.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 825,
            ],
            [
                'name' => 'USDT (BEP20)',
                'symbol' => 'USDT', 
                'image' => '/uploads/coins/21cfd7d.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 825,
            ],
            [
                'name' => 'USDT (ERC20)',
                'symbol' => 'USDT',
                'image' => '/uploads/coins/a04460b.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 825,
            ],
            [
                'name' => 'ETH',
                'symbol' => 'ETH',
                'image' => '/uploads/coins/4f4e48a.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 1027,
            ],
            [
                'name' => 'BTC',
                'symbol' => 'BTC',
                'image' => '/uploads/coins/18a48c1.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 1,
            ],
            [
                'name' => 'USDC',
                'symbol' => 'USDC',
                'image' => '/uploads/coins/8cf0a7f.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 3408,
            ],
            [
                'name' => 'TRX TRON',
                'symbol' => 'TRX',
                'image' => '/uploads/coins/48db22f.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 1958,
            ],
            [
                'name' => 'SOL',
                'symbol' => 'SOL',
                'image' => '/uploads/coins/ac31cde.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 5426,
            ],
            [
                'name' => 'Litecoin',
                'symbol' => 'LTC',
                'image' => '/uploads/coins/0b55362.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 2,
            ],
            [
                'name' => 'XMR',
                'symbol' => 'XMR',
                'image' => '/uploads/coins/7f41c16.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 328,
            ],
            [
                'name' => 'BUSD',
                'symbol' => 'BUSD',
                'image' => '/uploads/coins/0e8756b.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 4687,
            ],
            [
                'name' => 'PAYEER',
                'symbol' => 'PAYEER',
                'image' => '/uploads/coins/9c62ff6.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => null,
            ],
            [
                'name' => 'BNB Smart Chain',
                'symbol' => 'BNB',
                'image' => '/uploads/coins/50c0f61.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 1839,
            ],
            [
                'name' => 'SHIBA INU',
                'symbol' => 'SHIB',
                'image' => '/uploads/coins/ac69d04.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 5994,
            ],
            [
                'name' => 'STEPN',
                'symbol' => 'GMT',
                'image' => '/uploads/coins/b0ae936.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 18069,
            ],
            [
                'name' => 'Trust Wallet',
                'symbol' => 'TWT',
                'image' => '/uploads/coins/291685d.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 5964,
            ],
            [
                'name' => 'XRP',
                'symbol' => 'XRP',
                'image' => '/uploads/coins/7f40d03.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 52,
            ],
            [
                'name' => 'Polygon',
                'symbol' => 'MATIC',
                'image' => '/uploads/coins/a5f0ec2.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 3890,
            ],
            [
                'name' => 'BNB BEACON CHAIN',
                'symbol' => 'BNB',
                'image' => '/uploads/coins/e88c798.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => 1839,
            ],
            [
                'name' => 'BINANCE ID',
                'symbol' => 'BINANCE',
                'image' => '/uploads/coins/8549822.png',
                'is_active' => true,
                'type' => 'crypto',
                'static_course' => false,
                'coinmarketcap_id' => null,
            ],

            // Платежные системы (directions_to_ar)
            [
                'name' => 'Paypal',
                'symbol' => 'PAYPAL',
                'image' => '/uploads/coins/d67480d.png',
                'is_active' => true,
                'type' => 'fiat',
                'static_course' => true,
                'coinmarketcap_id' => null,
            ],
            [
                'name' => 'Skrill',
                'symbol' => 'SKRILL',
                'image' => '/uploads/coins/12dfb73.png',
                'is_active' => true,
                'type' => 'fiat',
                'static_course' => true,
                'coinmarketcap_id' => null,
            ],
            [
                'name' => 'Payoneer',
                'symbol' => 'PAYONEER',
                'image' => '/uploads/coins/ce99fc5.png',
                'is_active' => true,
                'type' => 'fiat',
                'static_course' => true,
                'coinmarketcap_id' => null,
            ],
            [
                'name' => 'TransferWise',
                'symbol' => 'WISE',
                'image' => '/uploads/coins/18b2890.png',
                'is_active' => true,
                'type' => 'fiat',
                'static_course' => true,
                'coinmarketcap_id' => null,
            ],
            [
                'name' => 'Cash App',
                'symbol' => 'CASHAPP',
                'image' => '/uploads/coins/6f635c5.png',
                'is_active' => true,
                'type' => 'fiat',
                'static_course' => true,
                'coinmarketcap_id' => null,
            ],
            [
                'name' => 'PAYEER',
                'symbol' => 'PAYEER',
                'image' => '/uploads/coins/9c62ff6.png',
                'is_active' => true,
                'type' => 'fiat',
                'static_course' => true,
                'coinmarketcap_id' => null,
            ],
            [
                'name' => 'Perfect Money USD',
                'symbol' => 'PM',
                'image' => '/uploads/coins/5142c11.png',
                'is_active' => true,
                'type' => 'fiat',
                'static_course' => true,
                'coinmarketcap_id' => null,
            ],
            [
                'name' => 'Revolut',
                'symbol' => 'REVOLUT',
                'image' => '/uploads/coins/5a4db6d.png',
                'is_active' => true,
                'type' => 'fiat',
                'static_course' => true,
                'coinmarketcap_id' => null,
            ],
        ];

        DB::table('currencies')->insert($currencies);
    }
}
